# Generated by Django 5.1 on 2025-01-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
