# Generated by Django 5.1 on 2025-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(default=1, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
