# Generated by Django 5.1 on 2025-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classiccardapplication',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
