# Generated by Django 5.1 on 2025-01-26 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_classiccardapplication_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
