# Generated by Django 5.1 on 2025-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_loanapplication_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
