# Generated by Django 5.1 on 2025-01-26 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_loanapplication_balance_due_alter_manager_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300, message='Credit score cannot be less than 300'), django.core.validators.MaxValueValidator(900, message='Credit score cannot exceed 900')])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('payment_history', models.IntegerField(default=0)),
                ('credit_utilization', models.IntegerField(default=0)),
                ('credit_history_length', models.IntegerField(default=0)),
                ('income_factor', models.IntegerField(default=0)),
                ('employment_factor', models.IntegerField(default=0)),
                ('age_factor', models.IntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
