# Generated by Django 5.1 on 2025-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_creditscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscore',
            name='credit_history_length',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score_at_application',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
