# Generated by Django 5.1 on 2025-01-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_loanapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='status',
        ),
    ]
