# Generated by Django 5.1 on 2025-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='has_missed_payments',
            field=models.BooleanField(default=False),
        ),
    ]
