# Generated by Django 5.1 on 2025-02-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_loanapplication_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=50)),
                ('expense_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('mutual_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.mutualfund')),
            ],
        ),
    ]
