# Generated by Django 5.1 on 2025-02-11 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_userotp_delete_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('passport', 'Passport'), ('utility_bills', 'Utility Bills')], max_length=20)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document_type')},
            },
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
