# Generated by Django 5.1 on 2025-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_userdocument_delete_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='has_verified_face',
            field=models.BooleanField(default=False),
        ),
    ]
