# Generated by Django 5.1 on 2025-02-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_customer_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
