# Generated by Django 5.2 on 2025-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_add_branch_model_and_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
